# Site Settings
title: Jared Teerlink - Data Scientist
description: Data Science Portfolio showcasing machine learning projects and analytics
author: Jared Teerlink
email: jteerlink@gmail.com # Replace with your actual email

# GitHub Pages Configuration
baseurl: "" # Empty for username.github.io sites
url: "https://jteerlink.github.io" # Your GitHub Pages URL

# Social Media
github_username: jteerlink
linkedin_username: jaredwteerlink

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging

paginate: 5
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir: tag
tag_page_layout: tag_page
tag_permalink_style: pretty

sass:
  sass_dir: _sass
  style: compressed